# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: start test server
          command: |
            ruby ruby/test_server.rb 8000
          background: true

      - run:
          name: run tests
          command: |
            make
